### ISSUE TITLE
Title handling with translations

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python-hugo-theme#398]
See https://github.com/scipy/scipy.org/issues/540

It is also happening for numpy.org. I suspect it is because they have the title appearing here:
```
languages:
  en:
    title: SciPy
    weight: 1
    contentDir: content/en
```
instead
```
title: Scientific Python
```

**Comment by stefanv** [comment]
`site.Params.title` should work in both cases.

**Comment by jarrodmillman** [comment]
Here is the template
```
{{- $navbarLogo     := .Site.Params.navbarlogo }}
{{- $navbarLogoShow := .Site.Params.navbarlogoshow }}
<nav id="nav" class="navbar is-fresh is-transparent no-shadow" role="navigation" aria-label="main navigation">
  <div class="container is-max-widescreen">
    <div class="navbar-brand">
      {{ if or (not .IsHome) ($navbarLogoShow) }}
      {{- if $navbarLogo}}
      <a class="navbar-item" href="{{ $navbarLogo.link }}">
        <img class="navbar-logo" src="{{ printf "/images/%s" $navbarLogo.image | relURL }}" alt="{{ default (printf "%s logo" $title) $navbarLogo.altText }}">
        <div class="navbar-logo-text">{{ default "" $navbarLogo.text }}</div>
      </a>
      {{- end}}
      {{ end }}
```

It looks like we expect
```
    params:
      description: Why SciPy? Fundamental algorithms. Broadly applicable. Foundational. Interoperable. Performant. Open source.
      navbarlogo:
        image: logo.svg
        altText: A blue circle with a snake in the shape of the letter 'S'.
        text: SciPy
        link: /
```
But we have
```
    params:
      description: Why SciPy? Fundamental algorithms. Broadly applicable. Foundational. Interoperable. Performant. Open source.
      navbarlogo:
        image: logo.svg
        altText: A blue circle with a snake in the shape of the letter 'S'.
        link: /
```
