### ISSUE TITLE
Column spanning row entries

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python-hugo-theme#8]
In [mailing-lists.md](https://github.com/jarrodmillman/scipy.org-new/blob/tables/content/en/mailing-lists.md), I have
```
{{< yamlToTable >}}


format:
  - align: left
  - align: left
  - align: right

rows:
  - columns:
    - "**SciPy-user**"
    - "[Archives](https://mail.python.org/pipermail/scipy-user/)"
    - "[Subscribe](https://mail.python.org/mailman/listinfo/scipy-user)"

  - columns:
    - Our user-support forum, for discussions of how to use SciPy.

  - columns:
    - "**SciPy-dev**"
    - "[Archives](https://mail.python.org/pipermail/scipy-dev/)"
    - "[Subscribe](https://mail.python.org/mailman/listinfo/scipy-dev)"

  - columns:
    - For discussions about SciPy development (code, website, docs, and more).

  - columns:
    - "**NumPy-discussion**"
    - "[Archives](https://mail.python.org/pipermail/numpy-discussion/)"
    - "[Subscribe](https://mail.python.org/mailman/listinfo/numpy-discussion/)"

  - columns:
    - For discussion of NumPy.

{{< /yamlToTable >}}
```
which is rendered as
![screenshot](https://user-images.githubusercontent.com/123428/135667768-fbc797f8-a604-4c5e-b90a-f57cf591b98c.png)

The descriptive text should span the columns like this
![screenshot](https://user-images.githubusercontent.com/123428/135667859-0ca08c3f-bb6e-4b33-a0b6-34925d0d8653.png)
